builds:
  - main: ./cmd/octant-kubeflow
    binary: ./octant-kubeflow
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -w

archives:
  -
    id: octant-kubeflow
    format: tar.gz
    files:
      - LICENSE
